[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "sphinx-benchmark"
version = "0.1.0"
description = "This is a Sphinx extension that benchmarks and profiles a docs build process event-wise(handler-wise), and the gaps in between the events-- so you can tell which extension, theme, or part of Sphinx itself is slowing your builds."
license = "BSD-3-Clause"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx>=9.1.0",
]

[[project.authors]]
name = "Aditi Juneja"
email = "aditijuneja7@gmail.com"

[project.urls]
"Bug Tracker" = 'https://github.com/Schefflera-Arboricola/sphinx-benchmark/issues'
"Source Code" = 'https://github.com/Schefflera-Arboricola/sphinx-benchmark'

[project.scripts]
sphinx-benchmark = "sphinx_benchmark.cli:main"

[dependency-groups]
test = [
    "pytest>=8.3",
]
dev = [
    { include-group = "test" },
    "pre-commit>=4.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/sphinx_benchmark"]
